# Generated by Django 3.0 on 2022-09-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genscan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='name',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='qrcode',
            old_name='qr_code',
            new_name='img',
        ),
    ]
