# Generated by Django 4.1.1 on 2022-09-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
