# Generated by Django 4.1.1 on 2022-09-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_email_confirmed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email_confirmed",
        ),
    ]
